baseurl = "https://bernas.engineer/"
languageCode = "en-US"
title = "bernas"
# Enable comments by entering your Disqus shortname
theme="coder"
languagecode = "en" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author = "João Costa" # Author's name.
    info = "Software Engineer" # Author's job title or info.
    description = "Bernas's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.

    #disqusShortname = "yourdiscussshortname" # Enable or disable Disqus

    # Wether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
	custom_css = []

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/jbddc/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/jbddc/"
[[params.social]]
    name = "Keybase"
    weight = 3
    url = "https://www.keybase.io/bernas"
[[params.social]]
    name = "LinkedIn"
    weight = 4
    url = "https://www.linkedin.com/in/joaobernardocosta/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
