baseurl = "https://bernas.gitlab.io/"
languageCode = "en-US"
title = "JB"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-115775057-1"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpg"
  author = "João Bernardo Costa"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "jbddc"
  Gitlab        = ""
  Twitter       = "jbddc"
  Email         = "jbernardoddc@gmail.com"
  LinkedIn      = ""
  Stackoverflow = ""
  Bitcoin       = ""
  Ethereum      = "0x6d1f59dDC82015793Aead51aC996ef2D418bdE2c"
  Steam         = "brenadr"
  Spotify       = "bernardoslr"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
#[[menu.main]]
#  name = "resume"
#  identifier = "resume"
#  weight = 300
#  url = "/resume/"
