baseurl = "https://jb.diasdacosta.com/"
languageCode = "en-US"
title = "João Bernardo"
# Enable comments by entering your Disqus shortname
theme = "coder"
languagecode = "en" # The site’s language code.

paginate = 20       # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2"                 # Color-theme or style for syntax highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
author = "João Bernardo Dias da Costa"           # Author's name.
info = "Machine Learning Engineer"               # Author's job title or info.
description = "João Bernardo's personal website" # Site description.
keywords = "blog,developer,personal"             # Site keywords.

#disqusShortname = "yourdiscussshortname" # Enable or disable Disqus

# Wether you want to hide copyright and credits in the footer.
hideCredits = true
hideCopyright = true
colorscheme = "auto"
hidecolorschemetoggle = false

# Custom CSS
custom_css = []

# Social links
[[params.social]]
name = "Email"
weight = 1
url = "mailto:joaobernardo@diasdacosta.com"
[[params.social]]
name = "Github"
weight = 2
url = "https://github.com/jbddc/"
[[params.social]]
name = "LinkedIn"
weight = 4
url = "https://www.linkedin.com/in/joaobernardocosta/"
[[params.social]]
name = "Instagram"
weight = 2
url = "https://instagram.com/os.meus.rolos/"

# Menu links
[[menu.main]]
name = "About"
weight = 2
url = "/about/"
[[menu.main]]
name = "🫖"
weight = 2
status = 418
url = "/teapot/"
